services:
  wedding-site:
    build: ./site
    container_name: wedding-site
    ports:
      - "8080:5000"
    volumes:
      - ./site/materials:/app/materials
      - ./site/src/static/images:/app/src/static/images
    environment:
      - FLASK_ENV=production
      - SQLITE_DB_PATH=/app/materials/wedding.db
      - ADMIN_PASSWORD=1410
      - MODEL=giga
      - SBER_API_KEY=MzJmOGNhMTQtYTI2My00MGQ1LWFmMDgtZmIzYTdmOTU4ZDlkOjVjOWUzNzcxLWZiZTYtNGJkZi1iNzRmLTBkMDg0NGQ4NDM5Zg==
      - DEEPSEEK_MODEL=deepseek-ai/DeepSeek-V4-Pro
      - AGENT_CLOUD_API_KEY=NDBiOTEzNzUtMjYwNy00ODI3LTgyZDgtZGFlNWUzY2FlZDBj.ccd73e0b27813b2e6cb2ad91cbbece77
      - AGENT_CLOUDRU_API_URL=https://foundation-models.api.cloud.ru/v1
      - USE_LOG=NO
      - INVITATION_BG_BLUR=5
      - INVITATION_BG_DARKEN=0.3
      - MAX_CONTENT_LENGTH_MB=250
    restart: unless-stopped

  wedding-site-dev:
    build: ./site
    container_name: wedding-site-dev
    ports:
      - "5050:5000"
    volumes:
      - ./site:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLITE_DB_PATH=/app/materials/wedding.db
      - ADMIN_PASSWORD=1410
      - MODEL=deepseek
      - SBER_API_KEY=MzJmOGNhMTQtYTI2My00MGQ1LWFmMDgtZmIzYTdmOTU4ZDlkOjVjOWUzNzcxLWZiZTYtNGJkZi1iNzRmLTBkMDg0NGQ4NDM5Zg==
      - DEEPSEEK_MODEL=deepseek-ai/DeepSeek-V4-Pro
      - AGENT_CLOUD_API_KEY=NDBiOTEzNzUtMjYwNy00ODI3LTgyZDgtZGFlNWUzY2FlZDBj.ccd73e0b27813b2e6cb2ad91cbbece77
      - AGENT_CLOUDRU_API_URL=https://foundation-models.api.cloud.ru/v1
      - USE_LOG=YES
      - INVITATION_BG_BLUR=5
      - INVITATION_BG_DARKEN=0.3
      - MAX_CONTENT_LENGTH_MB=250
    command: python src/app.py
    profiles:
      - dev
