#!/bin/bash
set -euo pipefail

: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"

: "${WEB_USER:=web_user}"
: "${WEB_PASSWORD:=web_pass}"
: "${BOT_USER:=bot_user}"
: "${BOT_PASSWORD:=bot_pass}"

# Подключаемся явно к нужной базе -- это важное исправление
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
CREATE USER "$WEB_USER" WITH PASSWORD '$WEB_PASSWORD';
CREATE USER "$BOT_USER" WITH PASSWORD '$BOT_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$WEB_USER";
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$BOT_USER";
-- переключаемся на базу (на всякий случай)
\connect "$POSTGRES_DB"
GRANT ALL PRIVILEGES ON SCHEMA public TO "$WEB_USER";
GRANT ALL PRIVILEGES ON SCHEMA public TO "$BOT_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$WEB_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$BOT_USER";
SQL