#!/bin/bash
set -euo pipefail

: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"

# можно переопределить через .env: WEB_USER, WEB_PASSWORD, BOT_USER, BOT_PASSWORD
: "${WEB_USER:=web_user}"
: "${WEB_PASSWORD:=web_pass}"
: "${BOT_USER:=bot_user}"
: "${BOT_PASSWORD:=bot_pass}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-SQL
CREATE USER "$WEB_USER" WITH PASSWORD '$WEB_PASSWORD';
CREATE USER "$BOT_USER" WITH PASSWORD '$BOT_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$WEB_USER";
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$BOT_USER";
\c "$POSTGRES_DB"
CREATE SCHEMA IF NOT EXISTS public;
GRANT ALL ON SCHEMA public TO "$WEB_USER";
GRANT ALL ON SCHEMA public TO "$BOT_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$WEB_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$BOT_USER";
SQL